// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// logdmvt_Rcpp
double logdmvt_Rcpp(const arma::vec& x, const arma::mat& S);
RcppExport SEXP _overconf-boot_logdmvt_Rcpp(SEXP xSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(logdmvt_Rcpp(x, S));
    return rcpp_result_gen;
END_RCPP
}
// generate_rows
arma::mat generate_rows(const double df, const arma::mat& design_mat, const arma::uword n_bss, const arma::uword n_parents);
RcppExport SEXP _overconf-boot_generate_rows(SEXP dfSEXP, SEXP design_matSEXP, SEXP n_bssSEXP, SEXP n_parentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design_mat(design_matSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type n_bss(n_bssSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type n_parents(n_parentsSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_rows(df, design_mat, n_bss, n_parents));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_overconf-boot_logdmvt_Rcpp", (DL_FUNC) &_overconf-boot_logdmvt_Rcpp, 2},
    {"_overconf-boot_generate_rows", (DL_FUNC) &_overconf-boot_generate_rows, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_overconf-boot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
