# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logdmvt_Rcpp <- function(x, S) {
    .Call(`_overconf-boot_logdmvt_Rcpp`, x, S)
}

generate_rows <- function(df, design_mat, n_bss, n_parents) {
    .Call(`_overconf-boot_generate_rows`, df, design_mat, n_bss, n_parents)
}

